// import './images/logo.svg'
import './scss/styles.scss'
// import './images/title_house.png'
// import './images/title_family.png'
// import './images/dots.png'
// import './images/mosaic_foto.png'
// import './images/management-image.png'
// import './images/main-news-image.svg'
// import './images/contact-us.png'
// import './images/our-blog1.png'
// import './images/our-blog2.png'
// import './images/our-blog3.png'
// import './images/combined-shape.svg'
// import './images/plus.svg'
// import './fonts/Roboto-Bold.eot'
// import './fonts/Roboto-Bold.otf'
// import './fonts/Roboto-Bold.svg'
// import './fonts/Roboto-Bold.ttf'
// import './fonts/Roboto-Bold.woff'
// import './fonts/Roboto-Regular.eot'
// import './fonts/Roboto-Regular.otf'
// import './fonts/Roboto-Regular.svg'
// import './fonts/Roboto-Regular.ttf'
// import './fonts/Roboto-Regular.woff'

// if (process.env.NODE_ENV !== 'production') {
//     require('file-loader!./index.html')
// }
